# These are supported funding model platforms

custom: [https://dandesign.camgirl.cloud/sponsor/, https://www.amazon.com/hz/wishlist/ls/1J7YZKQUYZ5AV?ref_=wl_share, https://www.amazon.com/hz/wishlist/ls/1LCKTM5X4531V?ref_=wl_share]
